-- Generated by kUML — schema for "LapisCloud"
-- Dialect: postgres

CREATE TABLE membership_tier (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    contribution_amount DECIMAL(12, 2) NOT NULL,
    billing_interval VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (billing_interval IN ('MONTHLY', 'QUARTERLY', 'YEARLY'))
);

CREATE TABLE document_folder (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    parent_folder_id UUID NULL
);

-- V0.4.1 Serienbrief/PDF engine: the issuing association's own letterhead/bank/Gemeinnuetzigkeit
-- data. Exactly one row by convention (see 11-organization-settings.kuml.kts file header) --
-- seeded unconditionally below (not via DevSeedData, which is opt-in/demo-gated and must never
-- gate a real capability like letterhead data existing at all).
CREATE TABLE organization_settings (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    street VARCHAR(200) NULL,
    postal_code VARCHAR(20) NULL,
    city VARCHAR(200) NULL,
    country VARCHAR(100) NULL,
    bank_iban VARCHAR(34) NULL,
    bank_bic VARCHAR(11) NULL,
    tax_exemption_authority VARCHAR(300) NULL,
    tax_exemption_date DATE NULL,
    is_political_party BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE committee (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(16) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    quorum_percent INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMP NOT NULL,
    CHECK (type IN ('EXECUTIVE_BOARD', 'WORKING_GROUP', 'COMMISSION', 'OTHER', 'GENERAL_ASSEMBLY'))
);

CREATE TABLE cost_center (
    id UUID NOT NULL PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ledger_account (
    id UUID NOT NULL PRIMARY KEY,
    account_number VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    account_class INTEGER NOT NULL,
    type VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    reserve_type VARCHAR(27) NULL,
    is_cash_register BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (type IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE')),
    CHECK (reserve_type IN ('PROJEKTRUECKLAGE', 'FREIE_RUECKLAGE', 'WIEDERBESCHAFFUNGSRUECKLAGE', 'BETRIEBSMITTELRUECKLAGE'))
);

CREATE TABLE member (
    id UUID NOT NULL PRIMARY KEY,
    display_name VARCHAR(200) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    status VARCHAR(11) NOT NULL,
    joined_at DATE NOT NULL,
    anonymized_at TIMESTAMP NULL,
    street VARCHAR(200) NULL,
    postal_code VARCHAR(20) NULL,
    city VARCHAR(200) NULL,
    country VARCHAR(100) NULL,
    membership_tier_id UUID NULL,
    CHECK (status IN ('ANTRAG', 'AKTIV', 'GAST', 'AUSGETRETEN'))
);

CREATE TABLE account (
    id UUID NOT NULL PRIMARY KEY,
    password_hash VARCHAR(200) NULL,
    oidc_subject VARCHAR(200) NULL,
    role VARCHAR(9) NOT NULL,
    member_id UUID NOT NULL,
    CHECK (role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN'))
);

CREATE TABLE contribution (
    id UUID NOT NULL PRIMARY KEY,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount_due DECIMAL(12, 2) NOT NULL,
    status VARCHAR(7) NOT NULL,
    paid_at TIMESTAMP NULL,
    paid_amount DECIMAL(12, 2) NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    membership_tier_id UUID NOT NULL,
    CHECK (status IN ('OPEN', 'PAID', 'WAIVED', 'OVERDUE'))
);

CREATE TABLE document (
    id UUID NOT NULL PRIMARY KEY,
    folder_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    current_version_id UUID NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    access_level VARCHAR(14) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (access_level IN ('PUBLIC_MEMBERS', 'BOARD_ONLY', 'ADMIN_ONLY'))
);

CREATE TABLE mailing_list (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    created_by UUID NOT NULL
);

CREATE TABLE direct_message (
    id UUID NOT NULL PRIMARY KEY,
    body VARCHAR(10000) NOT NULL,
    sender_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL
);

CREATE TABLE erasure_request (
    id UUID NOT NULL PRIMARY KEY,
    subject_member_id UUID NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    requested_by UUID NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    mode VARCHAR(31) NOT NULL,
    status VARCHAR(9) NOT NULL,
    decided_by UUID NULL,
    decided_at TIMESTAMP NULL,
    decision_note VARCHAR(1000) NULL,
    executed_at TIMESTAMP NULL,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    outcome_summary VARCHAR(8000) NULL,
    CHECK (mode IN ('ANONYMIZE', 'HARD_DELETE_WHERE_UNCONSTRAINED')),
    CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

CREATE TABLE committee_membership (
    id UUID NOT NULL PRIMARY KEY,
    role VARCHAR(12) NOT NULL,
    since DATE NOT NULL,
    until DATE NULL,
    committee_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR'))
);

CREATE TABLE ltr_balance (
    member_id UUID NOT NULL PRIMARY KEY,
    balance_ltr DECIMAL(18, 2) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE journal_entry (
    id UUID NOT NULL PRIMARY KEY,
    entry_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    voucher_reference VARCHAR(100) NULL,
    created_by UUID NOT NULL,
    status VARCHAR(6) NOT NULL,
    posted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    donor_member_id UUID NULL,
    CHECK (status IN ('DRAFT', 'POSTED'))
);

CREATE TABLE document_version (
    id UUID NOT NULL PRIMARY KEY,
    version_number INTEGER NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    uploaded_by UUID NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    change_note VARCHAR(1000) NULL,
    document_id UUID NOT NULL
);

CREATE TABLE meeting (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    location VARCHAR(300) NULL,
    format VARCHAR(9) NOT NULL,
    status VARCHAR(9) NOT NULL,
    called_by UUID NULL,
    called_at TIMESTAMP NULL,
    chair_member_id UUID NULL,
    minute_taker_member_id UUID NULL,
    protocol_document_id UUID NULL,
    created_at TIMESTAMP NOT NULL,
    committee_id UUID NOT NULL,
    CHECK (format IN ('IN_PERSON', 'ONLINE', 'HYBRID')),
    CHECK (status IN ('PLANNED', 'HELD', 'CANCELLED'))
);

CREATE TABLE mailing_list_subscription (
    id UUID NOT NULL PRIMARY KEY,
    subscribed_at TIMESTAMP NOT NULL,
    unsubscribed_at TIMESTAMP NULL,
    mailing_list_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE mailing_message (
    id UUID NOT NULL PRIMARY KEY,
    subject VARCHAR(300) NOT NULL,
    body_text VARCHAR(20000) NOT NULL,
    sent_by UUID NOT NULL,
    sent_at TIMESTAMP NULL,
    status VARCHAR(6) NOT NULL,
    mailing_list_id UUID NOT NULL,
    CHECK (status IN ('DRAFT', 'QUEUED', 'SENT', 'FAILED'))
);

CREATE TABLE dsgvo_audit_log (
    id UUID NOT NULL PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    actor_member_id UUID NULL,
    actor_role VARCHAR(9) NULL,
    action VARCHAR(17) NOT NULL,
    subject_member_id UUID NOT NULL,
    request_id UUID NULL,
    outcome_summary VARCHAR(8000) NULL,
    legal_basis VARCHAR(500) NULL,
    CHECK (actor_role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN')),
    CHECK (action IN ('EXPORT', 'ERASURE_REQUESTED', 'ERASURE_APPROVED', 'ERASURE_REJECTED', 'ERASURE_EXECUTED'))
);

CREATE TABLE posting (
    id UUID NOT NULL PRIMARY KEY,
    side VARCHAR(6) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    sphere VARCHAR(34) NOT NULL,
    journal_entry_id UUID NOT NULL,
    ledger_account_id UUID NOT NULL,
    cost_center_id UUID NULL,
    CHECK (side IN ('DEBIT', 'CREDIT')),
    CHECK (sphere IN ('IDEELLER_BEREICH', 'VERMOEGENSVERWALTUNG', 'ZWECKBETRIEB', 'WIRTSCHAFTLICHER_GESCHAEFTSBETRIEB'))
);

CREATE TABLE agenda_item (
    id UUID NOT NULL PRIMARY KEY,
    position INTEGER NOT NULL,
    title VARCHAR(300) NOT NULL,
    description VARCHAR(4000) NULL,
    presenter_member_id UUID NULL,
    meeting_id UUID NOT NULL
);

CREATE TABLE attendance (
    id UUID NOT NULL PRIMARY KEY,
    status VARCHAR(11) NOT NULL,
    represented_by_member_id UUID NULL,
    note VARCHAR(500) NULL,
    recorded_at TIMESTAMP NOT NULL,
    meeting_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (status IN ('PRESENT', 'EXCUSED', 'UNEXCUSED', 'REPRESENTED'))
);

CREATE TABLE mailing_delivery_log (
    id UUID NOT NULL PRIMARY KEY,
    delivered_at TIMESTAMP NOT NULL,
    delivery_status VARCHAR(20) NOT NULL,
    mailing_message_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (delivery_status IN ('SENT', 'BOUNCED', 'SKIPPED_UNSUBSCRIBED'))
);

CREATE TABLE resolution (
    id UUID NOT NULL PRIMARY KEY,
    number VARCHAR(50) NOT NULL,
    title VARCHAR(300) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    votes_yes INTEGER NOT NULL,
    votes_no INTEGER NOT NULL,
    votes_abstain INTEGER NOT NULL,
    quorum_met BOOLEAN NOT NULL,
    status VARCHAR(9) NOT NULL,
    decided_at TIMESTAMP NOT NULL,
    recorded_by UUID NOT NULL,
    resolution_mode VARCHAR(18) NOT NULL DEFAULT 'COMMITTEE_QUORUM',
    vote_id UUID NULL,
    election_id UUID NULL,
    systemic_consensus_id UUID NULL,
    meeting_id UUID NOT NULL,
    agenda_item_id UUID NULL,
    CHECK (status IN ('ADOPTED', 'REJECTED', 'POSTPONED')),
    CHECK (resolution_mode IN ('COMMITTEE_QUORUM', 'MERITOCRATIC', 'DEMOCRATIC', 'SYSTEMIC_CONSENSUS'))
);

CREATE TABLE motion (
    id UUID NOT NULL PRIMARY KEY,
    target_committee_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    rationale VARCHAR(4000) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    submitter_member_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    reviewed_by UUID NULL,
    reviewed_at TIMESTAMP NULL,
    review_note VARCHAR(1000) NULL,
    withdrawn_at TIMESTAMP NULL,
    meeting_id UUID NULL,
    agenda_item_id UUID NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('SUBMITTED', 'REVIEWED', 'REJECTED_PRELIMINARY', 'SCHEDULED', 'RESOLVED', 'REJECTED', 'POSTPONED', 'WITHDRAWN'))
);

CREATE TABLE vote (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(7) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP NULL,
    winner_option_id UUID NULL,
    second_price_ltr DECIMAL(18, 2) NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('OPEN', 'CLOSED', 'ABORTED'))
);

CREATE TABLE election (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    election_type VARCHAR(13) NOT NULL,
    secret BOOLEAN NOT NULL,
    seat_count INTEGER NOT NULL,
    target_committee_id UUID NULL,
    target_role VARCHAR(12) NULL,
    required_majority_percent INTEGER NOT NULL,
    status VARCHAR(23) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    candidate_list_approved_at TIMESTAMP NULL,
    voting_opened_at TIMESTAMP NULL,
    voting_closed_at TIMESTAMP NULL,
    tally_threshold INTEGER NOT NULL,
    tally_run_at TIMESTAMP NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (election_type IN ('YES_NO', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'LIST_VOTE', 'RANKED_CHOICE')),
    CHECK (target_role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR')),
    CHECK (status IN ('PREPARATION', 'CANDIDATE_LIST_RELEASED', 'OPEN', 'CLOSED', 'TALLIED', 'ABORTED'))
);

CREATE TABLE systemic_consensus (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(10) NOT NULL,
    secret BOOLEAN NOT NULL,
    scale_max INTEGER NOT NULL,
    aggregation VARCHAR(4) NOT NULL,
    tiebreak_rule VARCHAR(21) NOT NULL,
    group_conflict_viable_threshold DECIMAL(4, 3) NOT NULL,
    group_conflict_warn_threshold DECIMAL(4, 3) NOT NULL,
    status_quo_option_auto BOOLEAN NOT NULL,
    bindingness VARCHAR(8) NOT NULL,
    max_rounds INTEGER NOT NULL,
    round INTEGER NOT NULL,
    winner_option_id UUID NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    rating_opened_at TIMESTAMP NULL,
    rating_closed_at TIMESTAMP NULL,
    tally_run_at TIMESTAMP NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('COLLECTION', 'RATING', 'CLOSED', 'EVALUATED', 'ABORTED')),
    CHECK (aggregation IN ('MEAN', 'SUM')),
    CHECK (tiebreak_rule IN ('LOWEST_MAX_RESISTANCE', 'LOWEST_STD_DEV', 'REPEAT')),
    CHECK (bindingness IN ('ADVISORY', 'BINDING'))
);

CREATE TABLE vote_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    vote_id UUID NOT NULL
);

CREATE TABLE election_candidacy (
    id UUID NOT NULL PRIMARY KEY,
    motivation_text VARCHAR(1000) NULL,
    submitted_at TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_board_member (
    id UUID NOT NULL PRIMARY KEY,
    appointed_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_eligible_voter (
    id UUID NOT NULL PRIMARY KEY,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_participation (
    id UUID NOT NULL PRIMARY KEY,
    voted_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_tally_approval (
    id UUID NOT NULL PRIMARY KEY,
    approved_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_ballot (
    id UUID NOT NULL PRIMARY KEY,
    receipt_code VARCHAR(40) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NULL
);

CREATE TABLE systemic_consensus_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    is_status_quo_option BOOLEAN NOT NULL,
    systemic_consensus_id UUID NOT NULL,
    created_by UUID NOT NULL
);

CREATE TABLE systemic_consensus_eligible_voter (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_participation (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    voted_at TIMESTAMP NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_ballot (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    receipt_code VARCHAR(40) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NULL
);

CREATE TABLE vote_ballot (
    id UUID NOT NULL PRIMARY KEY,
    option_id UUID NOT NULL,
    stake_ltr DECIMAL(18, 2) NOT NULL,
    settled_ltr DECIMAL(18, 2) NULL,
    cast_at TIMESTAMP NOT NULL,
    vote_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    candidacy_id UUID NULL,
    election_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_resistance (
    id UUID NOT NULL PRIMARY KEY,
    resistance_value INTEGER NOT NULL,
    ballot_id UUID NOT NULL,
    option_id UUID NOT NULL
);

CREATE TABLE election_ballot_selection (
    id UUID NOT NULL PRIMARY KEY,
    ballot_id UUID NOT NULL,
    option_id UUID NOT NULL
);

-- Foreign Keys

ALTER TABLE member ADD CONSTRAINT fk_member_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE account ADD CONSTRAINT fk_account_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE document ADD CONSTRAINT fk_document_folder_id FOREIGN KEY (folder_id) REFERENCES document_folder(id);
ALTER TABLE document ADD CONSTRAINT fk_document_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_document_id FOREIGN KEY (document_id) REFERENCES document(id);
ALTER TABLE mailing_list ADD CONSTRAINT fk_mailing_list_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_sent_by FOREIGN KEY (sent_by) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_mailing_message_id FOREIGN KEY (mailing_message_id) REFERENCES mailing_message(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_sender_id FOREIGN KEY (sender_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_recipient_id FOREIGN KEY (recipient_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_requested_by FOREIGN KEY (requested_by) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_decided_by FOREIGN KEY (decided_by) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_actor_member_id FOREIGN KEY (actor_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_request_id FOREIGN KEY (request_id) REFERENCES erasure_request(id);
ALTER TABLE committee_membership ADD CONSTRAINT fk_committee_membership_committee_id FOREIGN KEY (committee_id) REFERENCES committee(id);
ALTER TABLE committee_membership ADD CONSTRAINT fk_committee_membership_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_called_by FOREIGN KEY (called_by) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_chair_member_id FOREIGN KEY (chair_member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_minute_taker_member_id FOREIGN KEY (minute_taker_member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_protocol_document_id FOREIGN KEY (protocol_document_id) REFERENCES document(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_committee_id FOREIGN KEY (committee_id) REFERENCES committee(id);
ALTER TABLE agenda_item ADD CONSTRAINT fk_agenda_item_presenter_member_id FOREIGN KEY (presenter_member_id) REFERENCES member(id);
ALTER TABLE agenda_item ADD CONSTRAINT fk_agenda_item_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_represented_by_member_id FOREIGN KEY (represented_by_member_id) REFERENCES member(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_recorded_by FOREIGN KEY (recorded_by) REFERENCES member(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_agenda_item_id FOREIGN KEY (agenda_item_id) REFERENCES agenda_item(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_target_committee_id FOREIGN KEY (target_committee_id) REFERENCES committee(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_submitter_member_id FOREIGN KEY (submitter_member_id) REFERENCES member(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES member(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_agenda_item_id FOREIGN KEY (agenda_item_id) REFERENCES agenda_item(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE vote_option ADD CONSTRAINT fk_vote_option_vote_id FOREIGN KEY (vote_id) REFERENCES vote(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_option_id FOREIGN KEY (option_id) REFERENCES vote_option(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_vote_id FOREIGN KEY (vote_id) REFERENCES vote(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election ADD CONSTRAINT fk_election_target_committee_id FOREIGN KEY (target_committee_id) REFERENCES committee(id);
ALTER TABLE election ADD CONSTRAINT fk_election_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE election ADD CONSTRAINT fk_election_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE election ADD CONSTRAINT fk_election_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE election ADD CONSTRAINT fk_election_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE election_candidacy ADD CONSTRAINT fk_election_candidacy_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_candidacy ADD CONSTRAINT fk_election_candidacy_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_option ADD CONSTRAINT fk_election_option_candidacy_id FOREIGN KEY (candidacy_id) REFERENCES election_candidacy(id);
ALTER TABLE election_option ADD CONSTRAINT fk_election_option_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_board_member ADD CONSTRAINT fk_election_board_member_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_board_member ADD CONSTRAINT fk_election_board_member_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_eligible_voter ADD CONSTRAINT fk_election_eligible_voter_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_eligible_voter ADD CONSTRAINT fk_election_eligible_voter_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_participation ADD CONSTRAINT fk_election_participation_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_participation ADD CONSTRAINT fk_election_participation_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_tally_approval ADD CONSTRAINT fk_election_tally_approval_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_tally_approval ADD CONSTRAINT fk_election_tally_approval_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_ballot ADD CONSTRAINT fk_election_ballot_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_ballot ADD CONSTRAINT fk_election_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_ballot_selection ADD CONSTRAINT fk_election_ballot_selection_ballot_id FOREIGN KEY (ballot_id) REFERENCES election_ballot(id);
ALTER TABLE election_ballot_selection ADD CONSTRAINT fk_election_ballot_selection_option_id FOREIGN KEY (option_id) REFERENCES election_option(id);
ALTER TABLE ltr_balance ADD CONSTRAINT fk_ltr_balance_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE systemic_consensus_option ADD CONSTRAINT fk_systemic_consensus_option_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_option ADD CONSTRAINT fk_systemic_consensus_option_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE systemic_consensus_eligible_voter ADD CONSTRAINT fk_systemic_consensus_eligible_voter_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_eligible_voter ADD CONSTRAINT fk_systemic_consensus_eligible_voter_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_participation ADD CONSTRAINT fk_systemic_consensus_participation_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_participation ADD CONSTRAINT fk_systemic_consensus_participation_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_ballot ADD CONSTRAINT fk_systemic_consensus_ballot_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_ballot ADD CONSTRAINT fk_systemic_consensus_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_resistance ADD CONSTRAINT fk_systemic_consensus_resistance_ballot_id FOREIGN KEY (ballot_id) REFERENCES systemic_consensus_ballot(id);
ALTER TABLE systemic_consensus_resistance ADD CONSTRAINT fk_systemic_consensus_resistance_option_id FOREIGN KEY (option_id) REFERENCES systemic_consensus_option(id);
ALTER TABLE journal_entry ADD CONSTRAINT fk_journal_entry_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE journal_entry ADD CONSTRAINT fk_journal_entry_donor_member_id FOREIGN KEY (donor_member_id) REFERENCES member(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_ledger_account_id FOREIGN KEY (ledger_account_id) REFERENCES ledger_account(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES cost_center(id);

-- Indexes

CREATE UNIQUE INDEX uq_account_member_id ON account (member_id);
CREATE UNIQUE INDEX uq_contribution_member_tier_period ON contribution (member_id, membership_tier_id, period_start, period_end);
CREATE INDEX idx_contribution_member ON contribution (member_id);
CREATE INDEX idx_contribution_status ON contribution (status);
CREATE INDEX idx_document_folder ON document (folder_id);
CREATE UNIQUE INDEX uq_document_version_number ON document_version (document_id, version_number);
CREATE INDEX idx_document_version_document ON document_version (document_id);
CREATE UNIQUE INDEX uq_mailing_subscription_list_member ON mailing_list_subscription (mailing_list_id, member_id);
CREATE INDEX idx_mailing_subscription_list ON mailing_list_subscription (mailing_list_id);
CREATE INDEX idx_mailing_message_list ON mailing_message (mailing_list_id);
CREATE INDEX idx_direct_message_recipient ON direct_message (recipient_id);
CREATE INDEX idx_direct_message_sender ON direct_message (sender_id);
CREATE INDEX idx_erasure_request_subject ON erasure_request (subject_member_id);
CREATE INDEX idx_erasure_request_status ON erasure_request (status);
CREATE INDEX idx_dsgvo_audit_log_subject ON dsgvo_audit_log (subject_member_id);
CREATE INDEX idx_dsgvo_audit_log_request ON dsgvo_audit_log (request_id);
CREATE INDEX idx_committee_membership_committee ON committee_membership (committee_id);
CREATE INDEX idx_committee_membership_member ON committee_membership (member_id);
CREATE INDEX idx_meeting_committee ON meeting (committee_id);
CREATE UNIQUE INDEX uq_agenda_item_position ON agenda_item (meeting_id, position);
CREATE INDEX idx_agenda_item_meeting ON agenda_item (meeting_id);
CREATE UNIQUE INDEX uq_attendance_member ON attendance (meeting_id, member_id);
CREATE INDEX idx_attendance_meeting ON attendance (meeting_id);
CREATE INDEX idx_resolution_meeting ON resolution (meeting_id);
CREATE INDEX idx_motion_target_committee ON motion (target_committee_id);
CREATE INDEX idx_motion_status ON motion (status);
CREATE INDEX idx_motion_submitter ON motion (submitter_member_id);
CREATE INDEX idx_motion_meeting ON motion (meeting_id);
CREATE INDEX idx_vote_motion ON vote (motion_id);
CREATE INDEX idx_vote_status ON vote (status);
CREATE INDEX idx_vote_option_vote ON vote_option (vote_id);
CREATE UNIQUE INDEX uq_vote_ballot_member ON vote_ballot (vote_id, member_id);
CREATE INDEX idx_vote_ballot_vote ON vote_ballot (vote_id);
CREATE INDEX idx_vote_ballot_member ON vote_ballot (member_id);
CREATE INDEX idx_election_motion ON election (motion_id);
CREATE INDEX idx_election_meeting ON election (meeting_id);
CREATE INDEX idx_election_status ON election (status);
CREATE INDEX idx_election_candidacy_election ON election_candidacy (election_id);
CREATE INDEX idx_election_candidacy_member ON election_candidacy (member_id);
CREATE INDEX idx_election_option_election ON election_option (election_id);
CREATE UNIQUE INDEX uq_election_board_member_member ON election_board_member (election_id, member_id);
CREATE INDEX idx_election_board_member_election ON election_board_member (election_id);
CREATE UNIQUE INDEX uq_election_eligible_voter_member ON election_eligible_voter (election_id, member_id);
CREATE INDEX idx_election_eligible_voter_election ON election_eligible_voter (election_id);
CREATE UNIQUE INDEX uq_election_participation_member ON election_participation (election_id, member_id);
CREATE INDEX idx_election_participation_election ON election_participation (election_id);
CREATE UNIQUE INDEX uq_election_tally_approval_member ON election_tally_approval (election_id, member_id);
CREATE INDEX idx_election_tally_approval_election ON election_tally_approval (election_id);
CREATE UNIQUE INDEX uq_election_ballot_member ON election_ballot (election_id, member_id);
CREATE INDEX idx_election_ballot_election ON election_ballot (election_id);
CREATE INDEX idx_election_ballot_selection_ballot ON election_ballot_selection (ballot_id);
CREATE INDEX idx_election_ballot_selection_option ON election_ballot_selection (option_id);
CREATE INDEX idx_systemic_consensus_motion ON systemic_consensus (motion_id);
CREATE INDEX idx_systemic_consensus_meeting ON systemic_consensus (meeting_id);
CREATE INDEX idx_systemic_consensus_status ON systemic_consensus (status);
CREATE INDEX idx_systemic_consensus_option_systemic_consensus ON systemic_consensus_option (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_eligible_voter_member_round ON systemic_consensus_eligible_voter (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_eligible_voter_systemic_consensus ON systemic_consensus_eligible_voter (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_participation_member_round ON systemic_consensus_participation (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_participation_systemic_consensus ON systemic_consensus_participation (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_ballot_member_round ON systemic_consensus_ballot (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_ballot_systemic_consensus ON systemic_consensus_ballot (systemic_consensus_id);
CREATE INDEX idx_systemic_consensus_resistance_ballot ON systemic_consensus_resistance (ballot_id);
CREATE INDEX idx_systemic_consensus_resistance_option ON systemic_consensus_resistance (option_id);
CREATE UNIQUE INDEX uq_ledger_account_number ON ledger_account (account_number);
CREATE INDEX idx_journal_entry_date ON journal_entry (entry_date);
CREATE INDEX idx_journal_entry_status ON journal_entry (status);
CREATE INDEX idx_posting_journal_entry ON posting (journal_entry_id);
CREATE INDEX idx_posting_ledger_account ON posting (ledger_account_id);
CREATE UNIQUE INDEX uq_cost_center_code ON cost_center (code);

-- V0.4.1 Serienbrief/PDF engine: exactly one organization_settings row must exist from first
-- migration onward, in every environment (not just LAPIS_SEED_DEMO_DATA=true demo deployments) --
-- unlike every other row in this codebase, letterhead data existing at all is a real capability
-- precondition, not sample/demo data, so it is seeded here directly rather than via DevSeedData.
-- Fixed sentinel id, mirrors DevSeedData's own '...-0000-0000000000f1' (standardTierId) pattern.
-- ADMIN can (and should) overwrite every field via updateOrganizationSettings afterward.
INSERT INTO organization_settings (id, name)
VALUES ('00000000-0000-0000-0000-0000000000f2', 'Verein/Partei (bitte in Organisationseinstellungen konfigurieren)');

