-- Generated by kUML — schema for "LapisCloud"
-- Dialect: postgres

CREATE TABLE membership_tier (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    contribution_amount DECIMAL(12, 2) NOT NULL,
    billing_interval VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (billing_interval IN ('MONTHLY', 'QUARTERLY', 'YEARLY'))
);

CREATE TABLE document_folder (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    parent_folder_id UUID NULL
);

-- V0.4.1 Serienbrief/PDF engine: the issuing association's own letterhead/bank/Gemeinnuetzigkeit
-- data. Exactly one row by convention (see 11-organization-settings.kuml.kts file header) --
-- seeded unconditionally below (not via DevSeedData, which is opt-in/demo-gated and must never
-- gate a real capability like letterhead data existing at all).
-- postal_mail_enabled (V0.4.2): explicit opt-in gate for Letterxpress postal-mail dispatch, see
-- that column's comment in 11-organization-settings.kuml.kts -- AVV requirement.
-- politician_ranking_enabled (V0.6.4): explicit opt-in gate for the Politiker-Profile/-Ranking
-- feature, see that column's comment in 11-organization-settings.kuml.kts.
CREATE TABLE organization_settings (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    street VARCHAR(200) NULL,
    postal_code VARCHAR(20) NULL,
    city VARCHAR(200) NULL,
    country VARCHAR(100) NULL,
    bank_iban VARCHAR(34) NULL,
    bank_bic VARCHAR(11) NULL,
    tax_exemption_authority VARCHAR(300) NULL,
    tax_exemption_date DATE NULL,
    is_political_party BOOLEAN NOT NULL DEFAULT FALSE,
    postal_mail_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    politician_ranking_enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE committee (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(16) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    quorum_percent INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMP NOT NULL,
    CHECK (type IN ('EXECUTIVE_BOARD', 'WORKING_GROUP', 'COMMISSION', 'OTHER', 'GENERAL_ASSEMBLY'))
);

CREATE TABLE cost_center (
    id UUID NOT NULL PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- V0.5.1 §25 PartG donor identity for a non-member donor (see 10-accounting.kuml.kts file header).
CREATE TABLE external_donor (
    id UUID NOT NULL PRIMARY KEY,
    display_name VARCHAR(300) NOT NULL,
    donor_category VARCHAR(41) NOT NULL,
    street VARCHAR(200) NULL,
    postal_code VARCHAR(20) NULL,
    city VARCHAR(200) NULL,
    country VARCHAR(100) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (donor_category IN (
        'GERMAN_NATURAL_PERSON', 'EU_NATURAL_PERSON', 'NON_EU_FOREIGN_NATURAL_PERSON',
        'GERMAN_COMPANY_OR_ORGANIZATION', 'PUBLIC_LAW_CORPORATION', 'OVER_25_PERCENT_STATE_OWNED_COMPANY',
        'OTHER_PARTY_OR_PARLIAMENTARY_GROUP_ENTITY', 'PROFESSIONAL_OR_TRADE_ASSOCIATION', 'ANONYMOUS'
    ))
);

CREATE TABLE ledger_account (
    id UUID NOT NULL PRIMARY KEY,
    account_number VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    account_class INTEGER NOT NULL,
    type VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    reserve_type VARCHAR(27) NULL,
    is_cash_register BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (type IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE')),
    CHECK (reserve_type IN ('PROJEKTRUECKLAGE', 'FREIE_RUECKLAGE', 'WIEDERBESCHAFFUNGSRUECKLAGE', 'BETRIEBSMITTELRUECKLAGE'))
);

CREATE TABLE member (
    id UUID NOT NULL PRIMARY KEY,
    display_name VARCHAR(200) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    status VARCHAR(11) NOT NULL,
    joined_at DATE NOT NULL,
    anonymized_at TIMESTAMP NULL,
    street VARCHAR(200) NULL,
    postal_code VARCHAR(20) NULL,
    city VARCHAR(200) NULL,
    country VARCHAR(100) NULL,
    date_of_birth DATE NULL,
    nationality VARCHAR(100) NULL,
    membership_tier_id UUID NULL,
    CHECK (status IN ('ANTRAG', 'AKTIV', 'GAST', 'AUSGETRETEN'))
);

CREATE TABLE account (
    id UUID NOT NULL PRIMARY KEY,
    password_hash VARCHAR(200) NULL,
    oidc_subject VARCHAR(200) NULL,
    role VARCHAR(9) NOT NULL,
    member_id UUID NOT NULL,
    CHECK (role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN'))
);

CREATE TABLE contribution (
    id UUID NOT NULL PRIMARY KEY,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount_due DECIMAL(12, 2) NOT NULL,
    status VARCHAR(7) NOT NULL,
    paid_at TIMESTAMP NULL,
    paid_amount DECIMAL(12, 2) NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    membership_tier_id UUID NOT NULL,
    CHECK (status IN ('OPEN', 'PAID', 'WAIVED', 'OVERDUE'))
);

CREATE TABLE document (
    id UUID NOT NULL PRIMARY KEY,
    folder_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    current_version_id UUID NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    access_level VARCHAR(14) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (access_level IN ('PUBLIC_MEMBERS', 'BOARD_ONLY', 'ADMIN_ONLY'))
);

CREATE TABLE mailing_list (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    created_by UUID NOT NULL
);

CREATE TABLE direct_message (
    id UUID NOT NULL PRIMARY KEY,
    body VARCHAR(10000) NOT NULL,
    sender_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL
);

CREATE TABLE erasure_request (
    id UUID NOT NULL PRIMARY KEY,
    subject_member_id UUID NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    requested_by UUID NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    mode VARCHAR(31) NOT NULL,
    status VARCHAR(9) NOT NULL,
    decided_by UUID NULL,
    decided_at TIMESTAMP NULL,
    decision_note VARCHAR(1000) NULL,
    executed_at TIMESTAMP NULL,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    outcome_summary TEXT NULL,
    CHECK (mode IN ('ANONYMIZE', 'HARD_DELETE_WHERE_UNCONSTRAINED')),
    CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

CREATE TABLE committee_membership (
    id UUID NOT NULL PRIMARY KEY,
    role VARCHAR(12) NOT NULL,
    since DATE NOT NULL,
    until DATE NULL,
    committee_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR'))
);

-- V0.6.1 Internes Crowdfunding: ltr_balance (a provisional balance SNAPSHOT, no ledger rows) is
-- replaced by ltr_ledger_entry, an append-only, signed-amount, per-member ledger -- see
-- 08-ltr-balance.kuml.kts file header for the full rationale. There was never a production
-- deployment of the pre-V0.6.1 schema, so this baseline is edited destructively (DROP + CREATE
-- inline) rather than adding a V2 migration -- consistent with this codebase's "V1__baseline.sql
-- is ONE consolidated migration" convention.
CREATE TABLE ltr_ledger_entry (
    id UUID NOT NULL PRIMARY KEY,
    entry_type VARCHAR(21) NOT NULL,
    amount_ltr DECIMAL(18, 2) NOT NULL,
    reference_type VARCHAR(20) NULL,
    reference_id UUID NULL,
    note VARCHAR(500) NULL,
    created_by UUID NULL,
    created_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    CHECK (entry_type IN ('MINT', 'PROJECT_STAKE', 'PROJECT_STAKE_RELEASE', 'VOTE_STAKE', 'PEER_TRANSFER_OUT', 'PEER_TRANSFER_IN')),
    CHECK (reference_type IN ('CROWDFUNDING_PROJECT', 'VOTE', 'PEER_TRANSFER'))
);

CREATE TABLE journal_entry (
    id UUID NOT NULL PRIMARY KEY,
    entry_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    voucher_reference VARCHAR(100) NULL,
    created_by UUID NOT NULL,
    status VARCHAR(6) NOT NULL,
    posted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    donor_member_id UUID NULL,
    donor_category VARCHAR(41) NULL,
    external_donor_id UUID NULL,
    CHECK (status IN ('DRAFT', 'POSTED')),
    CHECK (donor_category IN (
        'GERMAN_NATURAL_PERSON', 'EU_NATURAL_PERSON', 'NON_EU_FOREIGN_NATURAL_PERSON',
        'GERMAN_COMPANY_OR_ORGANIZATION', 'PUBLIC_LAW_CORPORATION', 'OVER_25_PERCENT_STATE_OWNED_COMPANY',
        'OTHER_PARTY_OR_PARLIAMENTARY_GROUP_ENTITY', 'PROFESSIONAL_OR_TRADE_ASSOCIATION', 'ANONYMOUS'
    ))
);

CREATE TABLE document_version (
    id UUID NOT NULL PRIMARY KEY,
    version_number INTEGER NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    uploaded_by UUID NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    change_note VARCHAR(1000) NULL,
    document_id UUID NOT NULL
);

CREATE TABLE meeting (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    location VARCHAR(300) NULL,
    format VARCHAR(9) NOT NULL,
    status VARCHAR(9) NOT NULL,
    called_by UUID NULL,
    called_at TIMESTAMP NULL,
    chair_member_id UUID NULL,
    minute_taker_member_id UUID NULL,
    protocol_document_id UUID NULL,
    created_at TIMESTAMP NOT NULL,
    committee_id UUID NOT NULL,
    CHECK (format IN ('IN_PERSON', 'ONLINE', 'HYBRID')),
    CHECK (status IN ('PLANNED', 'HELD', 'CANCELLED'))
);

CREATE TABLE mailing_list_subscription (
    id UUID NOT NULL PRIMARY KEY,
    subscribed_at TIMESTAMP NOT NULL,
    unsubscribed_at TIMESTAMP NULL,
    mailing_list_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE mailing_message (
    id UUID NOT NULL PRIMARY KEY,
    subject VARCHAR(300) NOT NULL,
    body_text VARCHAR(20000) NOT NULL,
    sent_by UUID NOT NULL,
    sent_at TIMESTAMP NULL,
    status VARCHAR(6) NOT NULL,
    mailing_list_id UUID NOT NULL,
    CHECK (status IN ('DRAFT', 'QUEUED', 'SENT', 'FAILED'))
);

CREATE TABLE dsgvo_audit_log (
    id UUID NOT NULL PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    actor_member_id UUID NULL,
    actor_role VARCHAR(9) NULL,
    action VARCHAR(17) NOT NULL,
    subject_member_id UUID NOT NULL,
    request_id UUID NULL,
    outcome_summary TEXT NULL,
    legal_basis VARCHAR(500) NULL,
    CHECK (actor_role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN')),
    CHECK (action IN ('EXPORT', 'ERASURE_REQUESTED', 'ERASURE_APPROVED', 'ERASURE_REJECTED', 'ERASURE_EXECUTED'))
);

CREATE TABLE posting (
    id UUID NOT NULL PRIMARY KEY,
    side VARCHAR(6) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    sphere VARCHAR(34) NOT NULL,
    journal_entry_id UUID NOT NULL,
    ledger_account_id UUID NOT NULL,
    cost_center_id UUID NULL,
    CHECK (side IN ('DEBIT', 'CREDIT')),
    CHECK (sphere IN ('IDEELLER_BEREICH', 'VERMOEGENSVERWALTUNG', 'ZWECKBETRIEB', 'WIRTSCHAFTLICHER_GESCHAEFTSBETRIEB'))
);

CREATE TABLE agenda_item (
    id UUID NOT NULL PRIMARY KEY,
    position INTEGER NOT NULL,
    title VARCHAR(300) NOT NULL,
    description VARCHAR(4000) NULL,
    presenter_member_id UUID NULL,
    meeting_id UUID NOT NULL
);

CREATE TABLE attendance (
    id UUID NOT NULL PRIMARY KEY,
    status VARCHAR(11) NOT NULL,
    represented_by_member_id UUID NULL,
    note VARCHAR(500) NULL,
    recorded_at TIMESTAMP NOT NULL,
    meeting_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (status IN ('PRESENT', 'EXCUSED', 'UNEXCUSED', 'REPRESENTED'))
);

CREATE TABLE mailing_delivery_log (
    id UUID NOT NULL PRIMARY KEY,
    delivered_at TIMESTAMP NOT NULL,
    delivery_status VARCHAR(20) NOT NULL,
    mailing_message_id UUID NOT NULL,
    member_id UUID NOT NULL,
    CHECK (delivery_status IN ('SENT', 'BOUNCED', 'SKIPPED_UNSUBSCRIBED'))
);

CREATE TABLE resolution (
    id UUID NOT NULL PRIMARY KEY,
    number VARCHAR(50) NOT NULL,
    title VARCHAR(300) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    votes_yes INTEGER NOT NULL,
    votes_no INTEGER NOT NULL,
    votes_abstain INTEGER NOT NULL,
    quorum_met BOOLEAN NOT NULL,
    status VARCHAR(9) NOT NULL,
    decided_at TIMESTAMP NOT NULL,
    recorded_by UUID NOT NULL,
    resolution_mode VARCHAR(18) NOT NULL DEFAULT 'COMMITTEE_QUORUM',
    vote_id UUID NULL,
    election_id UUID NULL,
    systemic_consensus_id UUID NULL,
    meeting_id UUID NOT NULL,
    agenda_item_id UUID NULL,
    CHECK (status IN ('ADOPTED', 'REJECTED', 'POSTPONED')),
    CHECK (resolution_mode IN ('COMMITTEE_QUORUM', 'MERITOCRATIC', 'DEMOCRATIC', 'SYSTEMIC_CONSENSUS'))
);

CREATE TABLE motion (
    id UUID NOT NULL PRIMARY KEY,
    target_committee_id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    rationale VARCHAR(4000) NOT NULL,
    text VARCHAR(4000) NOT NULL,
    submitter_member_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    reviewed_by UUID NULL,
    reviewed_at TIMESTAMP NULL,
    review_note VARCHAR(1000) NULL,
    withdrawn_at TIMESTAMP NULL,
    meeting_id UUID NULL,
    agenda_item_id UUID NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('SUBMITTED', 'REVIEWED', 'REJECTED_PRELIMINARY', 'SCHEDULED', 'RESOLVED', 'REJECTED', 'POSTPONED', 'WITHDRAWN'))
);

CREATE TABLE vote (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(7) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP NULL,
    winner_option_id UUID NULL,
    second_price_ltr DECIMAL(18, 2) NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('OPEN', 'CLOSED', 'ABORTED'))
);

CREATE TABLE election (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    election_type VARCHAR(13) NOT NULL,
    secret BOOLEAN NOT NULL,
    seat_count INTEGER NOT NULL,
    target_committee_id UUID NULL,
    target_role VARCHAR(12) NULL,
    required_majority_percent INTEGER NOT NULL,
    status VARCHAR(23) NOT NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    candidate_list_approved_at TIMESTAMP NULL,
    voting_opened_at TIMESTAMP NULL,
    voting_closed_at TIMESTAMP NULL,
    tally_threshold INTEGER NOT NULL,
    tally_run_at TIMESTAMP NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (election_type IN ('YES_NO', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'LIST_VOTE', 'RANKED_CHOICE')),
    CHECK (target_role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR')),
    CHECK (status IN ('PREPARATION', 'CANDIDATE_LIST_RELEASED', 'OPEN', 'CLOSED', 'TALLIED', 'ABORTED'))
);

CREATE TABLE systemic_consensus (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(10) NOT NULL,
    secret BOOLEAN NOT NULL,
    scale_max INTEGER NOT NULL,
    aggregation VARCHAR(4) NOT NULL,
    tiebreak_rule VARCHAR(21) NOT NULL,
    group_conflict_viable_threshold DECIMAL(4, 3) NOT NULL,
    group_conflict_warn_threshold DECIMAL(4, 3) NOT NULL,
    status_quo_option_auto BOOLEAN NOT NULL,
    bindingness VARCHAR(8) NOT NULL,
    max_rounds INTEGER NOT NULL,
    round INTEGER NOT NULL,
    winner_option_id UUID NULL,
    opened_by UUID NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    rating_opened_at TIMESTAMP NULL,
    rating_closed_at TIMESTAMP NULL,
    tally_run_at TIMESTAMP NULL,
    motion_id UUID NOT NULL,
    meeting_id UUID NOT NULL,
    resolution_id UUID NULL,
    CHECK (status IN ('COLLECTION', 'RATING', 'CLOSED', 'EVALUATED', 'ABORTED')),
    CHECK (aggregation IN ('MEAN', 'SUM')),
    CHECK (tiebreak_rule IN ('LOWEST_MAX_RESISTANCE', 'LOWEST_STD_DEV', 'REPEAT')),
    CHECK (bindingness IN ('ADVISORY', 'BINDING'))
);

CREATE TABLE vote_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    vote_id UUID NOT NULL
);

CREATE TABLE election_candidacy (
    id UUID NOT NULL PRIMARY KEY,
    motivation_text VARCHAR(1000) NULL,
    submitted_at TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_board_member (
    id UUID NOT NULL PRIMARY KEY,
    appointed_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_eligible_voter (
    id UUID NOT NULL PRIMARY KEY,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_participation (
    id UUID NOT NULL PRIMARY KEY,
    voted_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_tally_approval (
    id UUID NOT NULL PRIMARY KEY,
    approved_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_ballot (
    id UUID NOT NULL PRIMARY KEY,
    receipt_code VARCHAR(40) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    election_id UUID NOT NULL,
    member_id UUID NULL
);

CREATE TABLE systemic_consensus_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    is_status_quo_option BOOLEAN NOT NULL,
    systemic_consensus_id UUID NOT NULL,
    created_by UUID NOT NULL
);

CREATE TABLE systemic_consensus_eligible_voter (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_participation (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    voted_at TIMESTAMP NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_ballot (
    id UUID NOT NULL PRIMARY KEY,
    systemic_consensus_id UUID NOT NULL,
    receipt_code VARCHAR(40) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    round INTEGER NOT NULL,
    member_id UUID NULL
);

CREATE TABLE vote_ballot (
    id UUID NOT NULL PRIMARY KEY,
    option_id UUID NOT NULL,
    stake_ltr DECIMAL(18, 2) NOT NULL,
    settled_ltr DECIMAL(18, 2) NULL,
    cast_at TIMESTAMP NOT NULL,
    vote_id UUID NOT NULL,
    member_id UUID NOT NULL
);

CREATE TABLE election_option (
    id UUID NOT NULL PRIMARY KEY,
    label VARCHAR(200) NOT NULL,
    position INTEGER NOT NULL,
    candidacy_id UUID NULL,
    election_id UUID NOT NULL
);

CREATE TABLE systemic_consensus_resistance (
    id UUID NOT NULL PRIMARY KEY,
    resistance_value INTEGER NOT NULL,
    ballot_id UUID NOT NULL,
    option_id UUID NOT NULL
);

CREATE TABLE election_ballot_selection (
    id UUID NOT NULL PRIMARY KEY,
    ballot_id UUID NOT NULL,
    option_id UUID NOT NULL
);

-- V0.4.2 Letterxpress postal-mail dispatch: one row per physical-letter dispatch attempt.
CREATE TABLE postal_delivery_log (
    id UUID NOT NULL PRIMARY KEY,
    document_reference VARCHAR(300) NOT NULL,
    dispatched_at TIMESTAMP NOT NULL,
    status VARCHAR(6) NOT NULL,
    provider_reference VARCHAR(200) NULL,
    error_message VARCHAR(1000) NULL,
    recipient_member_id UUID NOT NULL,
    CHECK (status IN ('QUEUED', 'SENT', 'FAILED'))
);

-- V0.5.2 Transparenzregister (§20 GwG) beneficial-owner reminders. board_membership is a
-- Transparenzregister-facing beneficial-owner roster, parallel to (not a replacement of)
-- committee_membership -- see 13-transparenzregister.kuml.kts file header.
CREATE TABLE board_membership (
    id UUID NOT NULL PRIMARY KEY,
    committee_role VARCHAR(12) NOT NULL,
    started_at DATE NOT NULL,
    ended_at DATE NULL,
    member_id UUID NOT NULL,
    CHECK (committee_role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR'))
);

CREATE TABLE transparenzregister_reminder (
    id UUID NOT NULL PRIMARY KEY,
    triggered_at TIMESTAMP NOT NULL,
    committee_role VARCHAR(12) NOT NULL,
    change_type VARCHAR(6) NOT NULL,
    resolved BOOLEAN NOT NULL,
    resolved_at TIMESTAMP NULL,
    member_id UUID NOT NULL,
    resolved_by UUID NULL,
    CHECK (committee_role IN ('CHAIR', 'DEPUTY_CHAIR', 'SECRETARY', 'MEMBER', 'ASSESSOR')),
    CHECK (change_type IN ('JOINED', 'LEFT'))
);

-- V0.5.3 GoBD-Revisionssicherheit: hash-chained, append-only audit log (see
-- 14-audit-log.kuml.kts file header). audit_log_chain_state is a genesis-singleton row (exactly
-- one row, seeded below), mirroring organization_settings's own pattern -- a SELECT ... FOR UPDATE
-- on this one row is what serializes concurrent audit-log writers race-free, including for the
-- very first ("genesis") entry.
CREATE TABLE audit_log_chain_state (
    id UUID NOT NULL PRIMARY KEY,
    last_sequence_number BIGINT NOT NULL DEFAULT 0,
    last_entry_hash VARCHAR(64) NULL
);

CREATE TABLE audit_log_entry (
    id UUID NOT NULL PRIMARY KEY,
    sequence_number BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    actor_member_id UUID NULL,
    actor_role VARCHAR(9) NULL,
    entity_type VARCHAR(22) NOT NULL,
    entity_id UUID NOT NULL,
    action VARCHAR(6) NOT NULL,
    before_snapshot TEXT NULL,
    after_snapshot TEXT NULL,
    entry_hash VARCHAR(64) NOT NULL,
    previous_entry_hash VARCHAR(64) NULL,
    CHECK (actor_role IN ('MEMBER', 'BOARD', 'TREASURER', 'ADMIN')),
    CHECK (entity_type IN ('JOURNAL_ENTRY', 'PARTY_DONATION_VERDICT', 'RESOLUTION', 'BOARD_MEMBERSHIP')),
    CHECK (action IN ('CREATE', 'UPDATE', 'POST'))
);

-- V0.5.4 Backup-/Restore-/Datenexport-Garantie: one row per completed (or failed) full-organization
-- export/restore attempt (see 15-backup-export.kuml.kts file header for why this is deliberately
-- NOT part of the GoBD hash chain above).
CREATE TABLE backup_operation_log (
    id UUID NOT NULL PRIMARY KEY,
    operation_type VARCHAR(7) NOT NULL,
    status VARCHAR(9) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NOT NULL,
    bundle_format_version INT NOT NULL,
    table_count INT NOT NULL,
    total_row_count BIGINT NOT NULL,
    blob_count INT NOT NULL,
    blob_bytes_total BIGINT NOT NULL,
    bundle_size_bytes BIGINT NOT NULL,
    error_message VARCHAR(2000) NULL,
    actor_member_id UUID NOT NULL,
    CHECK (operation_type IN ('EXPORT', 'RESTORE')),
    CHECK (status IN ('SUCCEEDED', 'FAILED'))
);

-- V0.5.5 DSGVO-Vollausbau: AVV-Register/TOMs/DSFA-Vorlage/Datenpannenmeldung (see
-- 16-dsgvo-compliance.kuml.kts file header for the full domain rationale and legal-verification
-- disclaimer). Documentation-/workflow-tool support for a human-made legal decision -- avv_status,
-- dpia_required, authority_notification_required are always human input, never computed.
CREATE TABLE processing_agreement (
    id UUID NOT NULL PRIMARY KEY,
    processor_name VARCHAR(300) NOT NULL,
    processing_purpose TEXT NOT NULL,
    data_categories VARCHAR(2000) NOT NULL,
    avv_status VARCHAR(6) NOT NULL,
    signed_date DATE NULL,
    review_due_date DATE NULL,
    document_id UUID NULL,
    notes VARCHAR(2000) NULL,
    created_at TIMESTAMP NOT NULL,
    created_by UUID NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_by UUID NULL,
    CHECK (avv_status IN ('NONE', 'DRAFT', 'SIGNED'))
);

CREATE TABLE technical_organizational_measure (
    id UUID NOT NULL PRIMARY KEY,
    category VARCHAR(23) NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT NOT NULL,
    version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    created_by UUID NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_by UUID NULL,
    CHECK (
        category IN (
            'PHYSICAL_ACCESS_CONTROL', 'SYSTEM_ACCESS_CONTROL', 'DATA_ACCESS_CONTROL', 'TRANSFER_CONTROL',
            'INPUT_CONTROL', 'ORDER_CONTROL', 'AVAILABILITY_CONTROL', 'SEPARATION_CONTROL'
        )
    )
);

CREATE TABLE data_protection_impact_assessment (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    processing_description TEXT NOT NULL,
    necessity_proportionality TEXT NULL,
    risk_likelihood VARCHAR(6) NULL,
    risk_severity VARCHAR(6) NULL,
    risk_assessment TEXT NULL,
    mitigation_measures TEXT NULL,
    dpia_required BOOLEAN NULL,
    outcome_rationale TEXT NULL,
    status VARCHAR(19) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    created_by UUID NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_by UUID NULL,
    CHECK (risk_likelihood IN ('LOW', 'MEDIUM', 'HIGH')),
    CHECK (risk_severity IN ('LOW', 'MEDIUM', 'HIGH')),
    CHECK (status IN ('DRAFT', 'COMPLETED', 'OUTDATED_REVIEW_DUE'))
);

CREATE TABLE data_breach_incident (
    id UUID NOT NULL PRIMARY KEY,
    discovered_at TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    affected_data_categories VARCHAR(2000) NOT NULL,
    estimated_affected_persons INT NULL,
    risk_assessment TEXT NULL,
    risk_level VARCHAR(6) NULL,
    authority_notification_required BOOLEAN NULL,
    authority_notified_at TIMESTAMP NULL,
    data_subjects_notified_at TIMESTAMP NULL,
    status VARCHAR(24) NOT NULL,
    reported_at TIMESTAMP NOT NULL,
    reported_by UUID NOT NULL,
    updated_at TIMESTAMP NULL,
    updated_by UUID NULL,
    CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CHECK (status IN ('REPORTED', 'UNDER_ASSESSMENT', 'NOTIFIED_AUTHORITY', 'NO_NOTIFICATION_REQUIRED', 'CLOSED'))
);

-- V0.6.1 Internes Crowdfunding (see 17-crowdfunding.kuml.kts file header for the full fachlich
-- model). crowdfunding_submission_gate is a genesis-singleton lock row, mirroring
-- organization_settings/audit_log_chain_state's own pattern -- seeded below.
CREATE TABLE crowdfunding_project (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    submitter_member_id UUID NOT NULL,
    initial_weight_ltr DECIMAL(18, 2) NOT NULL,
    status VARCHAR(8) NOT NULL,
    rejection_reason VARCHAR(2000) NULL,
    reviewed_by UUID NULL,
    reviewed_at TIMESTAMP NULL,
    submitted_at TIMESTAMP NOT NULL,
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE crowdfunding_reaction (
    id UUID NOT NULL PRIMARY KEY,
    project_id UUID NOT NULL,
    reaction_value VARCHAR(7) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    CHECK (reaction_value IN ('LIKE', 'DISLIKE'))
);

CREATE TABLE crowdfunding_distribution (
    id UUID NOT NULL PRIMARY KEY,
    project_id UUID NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    basket_total_at_distribution INT NOT NULL,
    amount_eur DECIMAL(12, 2) NOT NULL,
    computed_at TIMESTAMP NOT NULL,
    triggered_by UUID NOT NULL
);

CREATE TABLE crowdfunding_submission_gate (
    id UUID NOT NULL PRIMARY KEY
);

-- V0.6.3 direkte LTR-Peer-to-Peer-Uebertragung (see 18-peer-transfer.kuml.kts file header for the
-- full fachlich model). Split from ltr_ledger_entry: this table carries the fachlich detail
-- (self-reported characterization, optional purpose), ltr_ledger_entry carries only the generic
-- signed booking effect (PEER_TRANSFER_OUT/PEER_TRANSFER_IN, referenceType=PEER_TRANSFER).
CREATE TABLE peer_transfer (
    id UUID NOT NULL PRIMARY KEY,
    amount_ltr DECIMAL(18, 2) NOT NULL,
    characterization VARCHAR(13) NOT NULL,
    purpose VARCHAR(500) NULL,
    sender_member_id UUID NOT NULL,
    recipient_member_id UUID NOT NULL,
    initiated_by UUID NULL,
    created_at TIMESTAMP NOT NULL,
    CHECK (characterization IN ('SCHENKUNG', 'HONORAR', 'PRIVATVERKAUF', 'SONSTIGES'))
);

-- V0.6.5 Price-Oracle fuer die Anker-Bindung (see 19-price-oracle.kuml.kts file header for the
-- full fachlich model). price_oracle_config is a single-row, ADMIN-tunable policy row, seeded
-- below, mirroring organization_settings/crowdfunding_submission_gate's own pattern -- no FK to
-- member. price_oracle_conversion is the permanent per-conversion provenance record; ltr_ledger_
-- entry_id is deliberately a plain, non-FK column (same polymorphic-pointer idiom
-- ltr_ledger_entry.reference_id already uses).
CREATE TABLE price_oracle_config (
    id UUID NOT NULL PRIMARY KEY,
    anchor_asset VARCHAR(11) NOT NULL,
    donation_currency VARCHAR(3) NOT NULL,
    anchor_units_per_ltr DECIMAL(38, 18) NOT NULL,
    cache_ttl_seconds INT NOT NULL,
    min_quorum INT NOT NULL,
    outlier_threshold_bps INT NOT NULL,
    max_spread_bps INT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CHECK (anchor_asset IN ('BITCOIN_BTC', 'GOLD_XAU', 'FIAT'))
);

CREATE TABLE price_oracle_conversion (
    id UUID NOT NULL PRIMARY KEY,
    donation_amount DECIMAL(18, 2) NOT NULL,
    donation_currency VARCHAR(3) NOT NULL,
    anchor_asset VARCHAR(11) NOT NULL,
    anchor_price DECIMAL(38, 18) NOT NULL,
    anchor_units_per_ltr DECIMAL(38, 18) NOT NULL,
    ltr_minted DECIMAL(18, 2) NOT NULL,
    price_status VARCHAR(8) NOT NULL,
    source_count INT NOT NULL,
    sources_used VARCHAR(500) NOT NULL,
    price_timestamp TIMESTAMP NOT NULL,
    ltr_ledger_entry_id UUID NOT NULL,
    created_by UUID NULL,
    created_at TIMESTAMP NOT NULL,
    member_id UUID NOT NULL,
    CHECK (anchor_asset IN ('BITCOIN_BTC', 'GOLD_XAU', 'FIAT')),
    CHECK (price_status IN ('LIVE', 'DEGRADED', 'CACHED', 'DEFERRED'))
);

-- V0.6.4 Politiker-Profile und Politiker-Ranking (see 20-politician.kuml.kts file header for the
-- full fachlich model; renumbered from 19-politician.kuml.kts to 20 when merged onto master
-- alongside V0.6.5, which independently claimed the same next-free slot 19 off the same V0.6.3
-- base -- no functional change from the rename). Re-grant after revocation reactivates the same
-- politician_profile row (member_id UNIQUE below) rather than inserting a second one.
CREATE TABLE politician_profile (
    id UUID NOT NULL PRIMARY KEY,
    member_id UUID NOT NULL,
    status VARCHAR(6) NOT NULL,
    mandate_text VARCHAR(2000) NULL,
    granted_at TIMESTAMP NOT NULL,
    granted_by_member_id UUID NOT NULL,
    revoked_at TIMESTAMP NULL,
    revoked_by_member_id UUID NULL,
    CHECK (status IN ('ACTIVE', 'FORMER'))
);

CREATE TABLE politician_reaction (
    id UUID NOT NULL PRIMARY KEY,
    politician_profile_id UUID NOT NULL,
    reaction_value VARCHAR(7) NOT NULL,
    cast_at TIMESTAMP NOT NULL,
    rater_member_id UUID NOT NULL,
    CHECK (reaction_value IN ('LIKE', 'DISLIKE'))
);

CREATE TABLE politician_weight_snapshot (
    id UUID NOT NULL PRIMARY KEY,
    politician_profile_id UUID NOT NULL,
    period_month DATE NOT NULL,
    member_trust_weight DECIMAL(18, 2) NOT NULL,
    member_like_count INT NOT NULL,
    member_dislike_count INT NOT NULL,
    computed_at TIMESTAMP NOT NULL,
    computed_by_member_id UUID NOT NULL
);

-- Foreign Keys

ALTER TABLE member ADD CONSTRAINT fk_member_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE account ADD CONSTRAINT fk_account_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE contribution ADD CONSTRAINT fk_contribution_membership_tier_id FOREIGN KEY (membership_tier_id) REFERENCES membership_tier(id);
ALTER TABLE document ADD CONSTRAINT fk_document_folder_id FOREIGN KEY (folder_id) REFERENCES document_folder(id);
ALTER TABLE document ADD CONSTRAINT fk_document_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES member(id);
ALTER TABLE document_version ADD CONSTRAINT fk_document_version_document_id FOREIGN KEY (document_id) REFERENCES document(id);
ALTER TABLE mailing_list ADD CONSTRAINT fk_mailing_list_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_list_subscription ADD CONSTRAINT fk_mailing_list_subscription_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_sent_by FOREIGN KEY (sent_by) REFERENCES member(id);
ALTER TABLE mailing_message ADD CONSTRAINT fk_mailing_message_mailing_list_id FOREIGN KEY (mailing_list_id) REFERENCES mailing_list(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_mailing_message_id FOREIGN KEY (mailing_message_id) REFERENCES mailing_message(id);
ALTER TABLE mailing_delivery_log ADD CONSTRAINT fk_mailing_delivery_log_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_sender_id FOREIGN KEY (sender_id) REFERENCES member(id);
ALTER TABLE direct_message ADD CONSTRAINT fk_direct_message_recipient_id FOREIGN KEY (recipient_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_requested_by FOREIGN KEY (requested_by) REFERENCES member(id);
ALTER TABLE erasure_request ADD CONSTRAINT fk_erasure_request_decided_by FOREIGN KEY (decided_by) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_actor_member_id FOREIGN KEY (actor_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_subject_member_id FOREIGN KEY (subject_member_id) REFERENCES member(id);
ALTER TABLE dsgvo_audit_log ADD CONSTRAINT fk_dsgvo_audit_log_request_id FOREIGN KEY (request_id) REFERENCES erasure_request(id);
ALTER TABLE committee_membership ADD CONSTRAINT fk_committee_membership_committee_id FOREIGN KEY (committee_id) REFERENCES committee(id);
ALTER TABLE committee_membership ADD CONSTRAINT fk_committee_membership_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_called_by FOREIGN KEY (called_by) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_chair_member_id FOREIGN KEY (chair_member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_minute_taker_member_id FOREIGN KEY (minute_taker_member_id) REFERENCES member(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_protocol_document_id FOREIGN KEY (protocol_document_id) REFERENCES document(id);
ALTER TABLE meeting ADD CONSTRAINT fk_meeting_committee_id FOREIGN KEY (committee_id) REFERENCES committee(id);
ALTER TABLE agenda_item ADD CONSTRAINT fk_agenda_item_presenter_member_id FOREIGN KEY (presenter_member_id) REFERENCES member(id);
ALTER TABLE agenda_item ADD CONSTRAINT fk_agenda_item_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_represented_by_member_id FOREIGN KEY (represented_by_member_id) REFERENCES member(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_recorded_by FOREIGN KEY (recorded_by) REFERENCES member(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE resolution ADD CONSTRAINT fk_resolution_agenda_item_id FOREIGN KEY (agenda_item_id) REFERENCES agenda_item(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_target_committee_id FOREIGN KEY (target_committee_id) REFERENCES committee(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_submitter_member_id FOREIGN KEY (submitter_member_id) REFERENCES member(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES member(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_agenda_item_id FOREIGN KEY (agenda_item_id) REFERENCES agenda_item(id);
ALTER TABLE motion ADD CONSTRAINT fk_motion_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE vote ADD CONSTRAINT fk_vote_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE vote_option ADD CONSTRAINT fk_vote_option_vote_id FOREIGN KEY (vote_id) REFERENCES vote(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_option_id FOREIGN KEY (option_id) REFERENCES vote_option(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_vote_id FOREIGN KEY (vote_id) REFERENCES vote(id);
ALTER TABLE vote_ballot ADD CONSTRAINT fk_vote_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election ADD CONSTRAINT fk_election_target_committee_id FOREIGN KEY (target_committee_id) REFERENCES committee(id);
ALTER TABLE election ADD CONSTRAINT fk_election_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE election ADD CONSTRAINT fk_election_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE election ADD CONSTRAINT fk_election_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE election ADD CONSTRAINT fk_election_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE election_candidacy ADD CONSTRAINT fk_election_candidacy_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_candidacy ADD CONSTRAINT fk_election_candidacy_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_option ADD CONSTRAINT fk_election_option_candidacy_id FOREIGN KEY (candidacy_id) REFERENCES election_candidacy(id);
ALTER TABLE election_option ADD CONSTRAINT fk_election_option_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_board_member ADD CONSTRAINT fk_election_board_member_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_board_member ADD CONSTRAINT fk_election_board_member_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_eligible_voter ADD CONSTRAINT fk_election_eligible_voter_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_eligible_voter ADD CONSTRAINT fk_election_eligible_voter_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_participation ADD CONSTRAINT fk_election_participation_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_participation ADD CONSTRAINT fk_election_participation_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_tally_approval ADD CONSTRAINT fk_election_tally_approval_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_tally_approval ADD CONSTRAINT fk_election_tally_approval_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_ballot ADD CONSTRAINT fk_election_ballot_election_id FOREIGN KEY (election_id) REFERENCES election(id);
ALTER TABLE election_ballot ADD CONSTRAINT fk_election_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE election_ballot_selection ADD CONSTRAINT fk_election_ballot_selection_ballot_id FOREIGN KEY (ballot_id) REFERENCES election_ballot(id);
ALTER TABLE election_ballot_selection ADD CONSTRAINT fk_election_ballot_selection_option_id FOREIGN KEY (option_id) REFERENCES election_option(id);
ALTER TABLE ltr_ledger_entry ADD CONSTRAINT fk_ltr_ledger_entry_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE ltr_ledger_entry ADD CONSTRAINT fk_ltr_ledger_entry_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_opened_by FOREIGN KEY (opened_by) REFERENCES member(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_motion_id FOREIGN KEY (motion_id) REFERENCES motion(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_meeting_id FOREIGN KEY (meeting_id) REFERENCES meeting(id);
ALTER TABLE systemic_consensus ADD CONSTRAINT fk_systemic_consensus_resolution_id FOREIGN KEY (resolution_id) REFERENCES resolution(id);
ALTER TABLE systemic_consensus_option ADD CONSTRAINT fk_systemic_consensus_option_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_option ADD CONSTRAINT fk_systemic_consensus_option_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE systemic_consensus_eligible_voter ADD CONSTRAINT fk_systemic_consensus_eligible_voter_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_eligible_voter ADD CONSTRAINT fk_systemic_consensus_eligible_voter_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_participation ADD CONSTRAINT fk_systemic_consensus_participation_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_participation ADD CONSTRAINT fk_systemic_consensus_participation_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_ballot ADD CONSTRAINT fk_systemic_consensus_ballot_systemic_consensus_id FOREIGN KEY (systemic_consensus_id) REFERENCES systemic_consensus(id);
ALTER TABLE systemic_consensus_ballot ADD CONSTRAINT fk_systemic_consensus_ballot_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE systemic_consensus_resistance ADD CONSTRAINT fk_systemic_consensus_resistance_ballot_id FOREIGN KEY (ballot_id) REFERENCES systemic_consensus_ballot(id);
ALTER TABLE systemic_consensus_resistance ADD CONSTRAINT fk_systemic_consensus_resistance_option_id FOREIGN KEY (option_id) REFERENCES systemic_consensus_option(id);
ALTER TABLE journal_entry ADD CONSTRAINT fk_journal_entry_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE journal_entry ADD CONSTRAINT fk_journal_entry_donor_member_id FOREIGN KEY (donor_member_id) REFERENCES member(id);
ALTER TABLE journal_entry ADD CONSTRAINT fk_journal_entry_external_donor_id FOREIGN KEY (external_donor_id) REFERENCES external_donor(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_ledger_account_id FOREIGN KEY (ledger_account_id) REFERENCES ledger_account(id);
ALTER TABLE posting ADD CONSTRAINT fk_posting_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES cost_center(id);
ALTER TABLE postal_delivery_log ADD CONSTRAINT fk_postal_delivery_log_recipient_member_id FOREIGN KEY (recipient_member_id) REFERENCES member(id);
ALTER TABLE board_membership ADD CONSTRAINT fk_board_membership_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE transparenzregister_reminder ADD CONSTRAINT fk_transparenzregister_reminder_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE transparenzregister_reminder ADD CONSTRAINT fk_transparenzregister_reminder_resolved_by FOREIGN KEY (resolved_by) REFERENCES member(id);
ALTER TABLE audit_log_entry ADD CONSTRAINT fk_audit_log_entry_actor_member_id FOREIGN KEY (actor_member_id) REFERENCES member(id);
ALTER TABLE backup_operation_log ADD CONSTRAINT fk_backup_operation_log_actor_member_id FOREIGN KEY (actor_member_id) REFERENCES member(id);
ALTER TABLE processing_agreement ADD CONSTRAINT fk_processing_agreement_document_id FOREIGN KEY (document_id) REFERENCES document(id);
ALTER TABLE processing_agreement ADD CONSTRAINT fk_processing_agreement_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE processing_agreement ADD CONSTRAINT fk_processing_agreement_updated_by FOREIGN KEY (updated_by) REFERENCES member(id);
ALTER TABLE technical_organizational_measure ADD CONSTRAINT fk_tom_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE technical_organizational_measure ADD CONSTRAINT fk_tom_updated_by FOREIGN KEY (updated_by) REFERENCES member(id);
ALTER TABLE data_protection_impact_assessment ADD CONSTRAINT fk_dpia_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE data_protection_impact_assessment ADD CONSTRAINT fk_dpia_updated_by FOREIGN KEY (updated_by) REFERENCES member(id);
ALTER TABLE data_breach_incident ADD CONSTRAINT fk_data_breach_incident_reported_by FOREIGN KEY (reported_by) REFERENCES member(id);
ALTER TABLE data_breach_incident ADD CONSTRAINT fk_data_breach_incident_updated_by FOREIGN KEY (updated_by) REFERENCES member(id);
ALTER TABLE crowdfunding_project ADD CONSTRAINT fk_crowdfunding_project_submitter_member_id FOREIGN KEY (submitter_member_id) REFERENCES member(id);
ALTER TABLE crowdfunding_project ADD CONSTRAINT fk_crowdfunding_project_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES member(id);
ALTER TABLE crowdfunding_reaction ADD CONSTRAINT fk_crowdfunding_reaction_project_id FOREIGN KEY (project_id) REFERENCES crowdfunding_project(id);
ALTER TABLE crowdfunding_reaction ADD CONSTRAINT fk_crowdfunding_reaction_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE crowdfunding_distribution ADD CONSTRAINT fk_crowdfunding_distribution_project_id FOREIGN KEY (project_id) REFERENCES crowdfunding_project(id);
ALTER TABLE crowdfunding_distribution ADD CONSTRAINT fk_crowdfunding_distribution_triggered_by FOREIGN KEY (triggered_by) REFERENCES member(id);
ALTER TABLE peer_transfer ADD CONSTRAINT fk_peer_transfer_sender_member_id FOREIGN KEY (sender_member_id) REFERENCES member(id);
ALTER TABLE peer_transfer ADD CONSTRAINT fk_peer_transfer_recipient_member_id FOREIGN KEY (recipient_member_id) REFERENCES member(id);
ALTER TABLE peer_transfer ADD CONSTRAINT fk_peer_transfer_initiated_by FOREIGN KEY (initiated_by) REFERENCES member(id);
ALTER TABLE price_oracle_conversion ADD CONSTRAINT fk_price_oracle_conversion_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE price_oracle_conversion ADD CONSTRAINT fk_price_oracle_conversion_created_by FOREIGN KEY (created_by) REFERENCES member(id);
ALTER TABLE politician_profile ADD CONSTRAINT fk_politician_profile_member_id FOREIGN KEY (member_id) REFERENCES member(id);
ALTER TABLE politician_profile ADD CONSTRAINT fk_politician_profile_granted_by_member_id FOREIGN KEY (granted_by_member_id) REFERENCES member(id);
ALTER TABLE politician_profile ADD CONSTRAINT fk_politician_profile_revoked_by_member_id FOREIGN KEY (revoked_by_member_id) REFERENCES member(id);
ALTER TABLE politician_reaction ADD CONSTRAINT fk_politician_reaction_politician_profile_id FOREIGN KEY (politician_profile_id) REFERENCES politician_profile(id);
ALTER TABLE politician_reaction ADD CONSTRAINT fk_politician_reaction_rater_member_id FOREIGN KEY (rater_member_id) REFERENCES member(id);
ALTER TABLE politician_weight_snapshot ADD CONSTRAINT fk_politician_weight_snapshot_politician_profile_id FOREIGN KEY (politician_profile_id) REFERENCES politician_profile(id);
ALTER TABLE politician_weight_snapshot ADD CONSTRAINT fk_politician_weight_snapshot_computed_by_member_id FOREIGN KEY (computed_by_member_id) REFERENCES member(id);

-- Indexes

CREATE UNIQUE INDEX uq_account_member_id ON account (member_id);
CREATE UNIQUE INDEX uq_contribution_member_tier_period ON contribution (member_id, membership_tier_id, period_start, period_end);
CREATE INDEX idx_contribution_member ON contribution (member_id);
CREATE INDEX idx_contribution_status ON contribution (status);
CREATE INDEX idx_document_folder ON document (folder_id);
CREATE UNIQUE INDEX uq_document_version_number ON document_version (document_id, version_number);
CREATE INDEX idx_document_version_document ON document_version (document_id);
CREATE UNIQUE INDEX uq_mailing_subscription_list_member ON mailing_list_subscription (mailing_list_id, member_id);
CREATE INDEX idx_mailing_subscription_list ON mailing_list_subscription (mailing_list_id);
CREATE INDEX idx_mailing_message_list ON mailing_message (mailing_list_id);
CREATE INDEX idx_direct_message_recipient ON direct_message (recipient_id);
CREATE INDEX idx_direct_message_sender ON direct_message (sender_id);
CREATE INDEX idx_erasure_request_subject ON erasure_request (subject_member_id);
CREATE INDEX idx_erasure_request_status ON erasure_request (status);
CREATE INDEX idx_dsgvo_audit_log_subject ON dsgvo_audit_log (subject_member_id);
CREATE INDEX idx_dsgvo_audit_log_request ON dsgvo_audit_log (request_id);
CREATE INDEX idx_committee_membership_committee ON committee_membership (committee_id);
CREATE INDEX idx_committee_membership_member ON committee_membership (member_id);
CREATE INDEX idx_meeting_committee ON meeting (committee_id);
CREATE UNIQUE INDEX uq_agenda_item_position ON agenda_item (meeting_id, position);
CREATE INDEX idx_agenda_item_meeting ON agenda_item (meeting_id);
CREATE UNIQUE INDEX uq_attendance_member ON attendance (meeting_id, member_id);
CREATE INDEX idx_attendance_meeting ON attendance (meeting_id);
CREATE INDEX idx_resolution_meeting ON resolution (meeting_id);
CREATE INDEX idx_motion_target_committee ON motion (target_committee_id);
CREATE INDEX idx_motion_status ON motion (status);
CREATE INDEX idx_motion_submitter ON motion (submitter_member_id);
CREATE INDEX idx_motion_meeting ON motion (meeting_id);
CREATE INDEX idx_vote_motion ON vote (motion_id);
CREATE INDEX idx_vote_status ON vote (status);
CREATE INDEX idx_vote_option_vote ON vote_option (vote_id);
CREATE UNIQUE INDEX uq_vote_ballot_member ON vote_ballot (vote_id, member_id);
CREATE INDEX idx_vote_ballot_vote ON vote_ballot (vote_id);
CREATE INDEX idx_vote_ballot_member ON vote_ballot (member_id);
CREATE INDEX idx_election_motion ON election (motion_id);
CREATE INDEX idx_election_meeting ON election (meeting_id);
CREATE INDEX idx_election_status ON election (status);
CREATE INDEX idx_election_candidacy_election ON election_candidacy (election_id);
CREATE INDEX idx_election_candidacy_member ON election_candidacy (member_id);
CREATE INDEX idx_election_option_election ON election_option (election_id);
CREATE UNIQUE INDEX uq_election_board_member_member ON election_board_member (election_id, member_id);
CREATE INDEX idx_election_board_member_election ON election_board_member (election_id);
CREATE UNIQUE INDEX uq_election_eligible_voter_member ON election_eligible_voter (election_id, member_id);
CREATE INDEX idx_election_eligible_voter_election ON election_eligible_voter (election_id);
CREATE UNIQUE INDEX uq_election_participation_member ON election_participation (election_id, member_id);
CREATE INDEX idx_election_participation_election ON election_participation (election_id);
CREATE UNIQUE INDEX uq_election_tally_approval_member ON election_tally_approval (election_id, member_id);
CREATE INDEX idx_election_tally_approval_election ON election_tally_approval (election_id);
CREATE UNIQUE INDEX uq_election_ballot_member ON election_ballot (election_id, member_id);
CREATE INDEX idx_election_ballot_election ON election_ballot (election_id);
CREATE INDEX idx_election_ballot_selection_ballot ON election_ballot_selection (ballot_id);
CREATE INDEX idx_election_ballot_selection_option ON election_ballot_selection (option_id);
CREATE INDEX idx_systemic_consensus_motion ON systemic_consensus (motion_id);
CREATE INDEX idx_systemic_consensus_meeting ON systemic_consensus (meeting_id);
CREATE INDEX idx_systemic_consensus_status ON systemic_consensus (status);
CREATE INDEX idx_systemic_consensus_option_systemic_consensus ON systemic_consensus_option (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_eligible_voter_member_round ON systemic_consensus_eligible_voter (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_eligible_voter_systemic_consensus ON systemic_consensus_eligible_voter (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_participation_member_round ON systemic_consensus_participation (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_participation_systemic_consensus ON systemic_consensus_participation (systemic_consensus_id);
CREATE UNIQUE INDEX uq_systemic_consensus_ballot_member_round ON systemic_consensus_ballot (systemic_consensus_id, member_id, round);
CREATE INDEX idx_systemic_consensus_ballot_systemic_consensus ON systemic_consensus_ballot (systemic_consensus_id);
CREATE INDEX idx_systemic_consensus_resistance_ballot ON systemic_consensus_resistance (ballot_id);
CREATE INDEX idx_systemic_consensus_resistance_option ON systemic_consensus_resistance (option_id);
CREATE UNIQUE INDEX uq_ledger_account_number ON ledger_account (account_number);
CREATE INDEX idx_journal_entry_date ON journal_entry (entry_date);
CREATE INDEX idx_journal_entry_status ON journal_entry (status);
CREATE INDEX idx_posting_journal_entry ON posting (journal_entry_id);
CREATE INDEX idx_posting_ledger_account ON posting (ledger_account_id);
CREATE UNIQUE INDEX uq_cost_center_code ON cost_center (code);
CREATE INDEX idx_postal_delivery_log_recipient ON postal_delivery_log (recipient_member_id);
CREATE INDEX idx_board_membership_member ON board_membership (member_id);
CREATE INDEX idx_transparenzregister_reminder_member ON transparenzregister_reminder (member_id);
CREATE INDEX idx_transparenzregister_reminder_resolved ON transparenzregister_reminder (resolved);
CREATE UNIQUE INDEX uq_audit_log_entry_sequence ON audit_log_entry (sequence_number);
CREATE INDEX idx_audit_log_entry_entity_id ON audit_log_entry (entity_id);
CREATE INDEX idx_audit_log_entry_occurred_at ON audit_log_entry (occurred_at);
CREATE INDEX idx_backup_operation_log_actor ON backup_operation_log (actor_member_id);
CREATE INDEX idx_processing_agreement_status ON processing_agreement (avv_status);
CREATE INDEX idx_processing_agreement_created_by ON processing_agreement (created_by);
CREATE INDEX idx_tom_category ON technical_organizational_measure (category);
CREATE INDEX idx_dpia_status ON data_protection_impact_assessment (status);
CREATE INDEX idx_breach_status ON data_breach_incident (status);
CREATE INDEX idx_breach_reported_by ON data_breach_incident (reported_by);
CREATE INDEX idx_ltr_ledger_entry_member ON ltr_ledger_entry (member_id);
CREATE INDEX idx_ltr_ledger_entry_type ON ltr_ledger_entry (entry_type);
CREATE INDEX idx_crowdfunding_project_status ON crowdfunding_project (status);
CREATE INDEX idx_crowdfunding_project_submitter ON crowdfunding_project (submitter_member_id);
CREATE UNIQUE INDEX uq_crowdfunding_reaction_project_member ON crowdfunding_reaction (project_id, member_id);
CREATE INDEX idx_crowdfunding_reaction_project ON crowdfunding_reaction (project_id);
CREATE UNIQUE INDEX uq_crowdfunding_distribution_project_period ON crowdfunding_distribution (project_id, period_start, period_end);
CREATE INDEX idx_peer_transfer_sender ON peer_transfer (sender_member_id);
CREATE INDEX idx_peer_transfer_recipient ON peer_transfer (recipient_member_id);
CREATE INDEX idx_politician_profile_status ON politician_profile (status);
CREATE UNIQUE INDEX uq_politician_profile_member ON politician_profile (member_id);
CREATE UNIQUE INDEX uq_politician_reaction_profile_rater ON politician_reaction (politician_profile_id, rater_member_id);
CREATE INDEX idx_politician_reaction_profile ON politician_reaction (politician_profile_id);
CREATE UNIQUE INDEX uq_politician_weight_snapshot_profile_period ON politician_weight_snapshot (politician_profile_id, period_month);

CREATE INDEX idx_price_oracle_conversion_member ON price_oracle_conversion (member_id);

-- V0.4.1 Serienbrief/PDF engine: exactly one organization_settings row must exist from first
-- migration onward, in every environment (not just LAPIS_SEED_DEMO_DATA=true demo deployments) --
-- unlike every other row in this codebase, letterhead data existing at all is a real capability
-- precondition, not sample/demo data, so it is seeded here directly rather than via DevSeedData.
-- Fixed sentinel id, mirrors DevSeedData's own '...-0000-0000000000f1' (standardTierId) pattern.
-- ADMIN can (and should) overwrite every field via updateOrganizationSettings afterward.
INSERT INTO organization_settings (id, name)
VALUES ('00000000-0000-0000-0000-0000000000f2', 'Verein/Partei (bitte in Organisationseinstellungen konfigurieren)');

-- V0.5.3 GoBD-Revisionssicherheit: exactly one audit_log_chain_state row must exist from first
-- migration onward -- the genesis-singleton row AuditLogRecorder locks (SELECT ... FOR UPDATE) to
-- serialize concurrent audit-log writers and assign gapless sequence numbers, including for the
-- very first entry. Fixed sentinel id, next unused '...-0000-0000000000fN' slot after
-- organization_settings's own '...-f2'. last_entry_hash starts NULL (no entry written yet).
INSERT INTO audit_log_chain_state (id, last_sequence_number, last_entry_hash)
VALUES ('00000000-0000-0000-0000-0000000000f3', 0, NULL);

-- V0.6.1 Internes Crowdfunding: exactly one crowdfunding_submission_gate row must exist from
-- first migration onward -- the genesis-singleton row CrowdfundingService.submitProject locks
-- (SELECT ... FOR UPDATE) to serialize concurrent project submissions against the same decaying
-- top-weight entry hurdle. Fixed sentinel id, next unused '...-0000-0000000000fN' slot after
-- audit_log_chain_state's own '...-f3'. No other columns -- see 17-crowdfunding.kuml.kts file
-- header. Also registered in OrganizationRestoreService.SEEDED_SINGLETON_ROWS so a fresh restore
-- target is not mistaken for "already holds data".
INSERT INTO crowdfunding_submission_gate (id)
VALUES ('00000000-0000-0000-0000-0000000000f4');

-- V0.6.5 Price-Oracle fuer die Anker-Bindung: exactly one price_oracle_config row must exist from
-- first migration onward -- ADMIN can (and should) retune every field via updateOracleConfig
-- afterward. Fixed sentinel id, next unused '...-0000-0000000000fN' slot after
-- crowdfunding_submission_gate's own '...-f4'. Seeded defaults: BITCOIN_BTC anchor, EUR donation
-- currency, a placeholder peg (1 LTR = 0.000001 BTC), 300s cache TTL, quorum 2 (of 3 configured
-- BTC sources), 3% (300bps) outlier-rejection threshold, 10% (1000bps) max survivor spread before
-- halting. See 19-price-oracle.kuml.kts file header. Also registered in
-- OrganizationRestoreService.SEEDED_SINGLETON_ROWS so a fresh restore target is not mistaken for
-- "already holds data".
INSERT INTO price_oracle_config
    (id, anchor_asset, donation_currency, anchor_units_per_ltr,
     cache_ttl_seconds, min_quorum, outlier_threshold_bps, max_spread_bps, updated_at)
VALUES ('00000000-0000-0000-0000-0000000000f5', 'BITCOIN_BTC', 'EUR', 0.000001,
    300, 2, 300, 1000, CURRENT_TIMESTAMP);

